// Generated by CoffeeScript 1.5.0
var MickrigTestCase;

MickrigTestCase = function(name) {
  var tests;
  tests = new Array();
  return {
    test: function(name, test) {
      return tests.push({
        n: name,
        t: test
      });
    },
    runTest: function(test) {
      try {
        test.t();
        return "Test '" + test.n + "' successful";
      } catch (error) {
        return "Test '" + test.n + "' failed: " + error;
      }
    },
    run: function() {
      var messages, test, _i, _len;
      messages = [];
      messages.push("Running TestCase " + (name || ""));
      for (_i = 0, _len = tests.length; _i < _len; _i++) {
        test = tests[_i];
        messages.push(this.runTest(test));
      }
      return messages;
    }
  };
};
