// Generated by CoffeeScript 1.5.0
var expect;

expect = function(test, desc) {
  var check, expectations, truthy;
  truthy = true;
  check = function(toCheck, checkValue) {
    if (toCheck === truthy) {
      return true;
    } else {
      throw "expected '" + (desc ? desc : test) + "' " + (truthy ? "to be" : "not to be") + (" '" + checkValue + "'");
    }
  };
  expectations = {
    be: function(value) {
      return check(test === value, value);
    },
    beTrue: function() {
      return check(test === true, "true");
    },
    beFalse: function() {
      return check(test === false, "false");
    }
  };
  return {
    notTo: function() {
      truthy = false;
      return expectations;
    },
    to: function() {
      truthy = true;
      return expectations;
    }
  };
};
