// Generated by CoffeeScript 2.0.0-alpha1
var MickrigTestCase;

module.exports = MickrigTestCase = function(name) {
  var tests;
  tests = new Array();
  return {
    test: function(name, test) {
      return tests.push({
        n: name,
        t: test
      });
    },
    runTest: function(test) {
      var error;
      try {
        test.t();
        return "Test '" + test.n + "' successful";
      } catch (error1) {
        error = error1;
        return "Test '" + test.n + "' failed: " + error;
      }
    },
    run: function() {
      var i, len, messages, test;
      messages = [];
      messages.push("Running TestCase " + (name || ""));
      for (i = 0, len = tests.length; i < len; i++) {
        test = tests[i];
        messages.push(this.runTest(test));
      }
      return messages;
    }
  };
};
